// Dữ liệu emoji cho bộ chọn trong mind map: chia nhóm + từ khoá để tìm kiếm.
// Tự chứa (không phụ thuộc thư viện ngoài) để hợp với app đóng gói offline.

export interface EmojiCat { key: string; label: string; tab: string }

export const EMOJI_CATS: EmojiCat[] = [
  { key: 'smileys', label: 'Mặt cười & cảm xúc', tab: '😀' },
  { key: 'people', label: 'Con người & cử chỉ', tab: '👍' },
  { key: 'animals', label: 'Động vật & thiên nhiên', tab: '🐻' },
  { key: 'food', label: 'Đồ ăn & uống', tab: '🍔' },
  { key: 'activity', label: 'Hoạt động', tab: '⚽' },
  { key: 'travel', label: 'Du lịch & nơi chốn', tab: '🚗' },
  { key: 'objects', label: 'Đồ vật', tab: '💡' },
  { key: 'symbols', label: 'Ký hiệu', tab: '❤️' },
  { key: 'flags', label: 'Cờ', tab: '🏁' },
];

// Mỗi mục: [emoji, từ khoá để tìm].
export const EMOJIS: Record<string, [string, string][]> = {
  smileys: [
    ['😀', 'grin cuoi happy'], ['😃', 'smile cuoi'], ['😄', 'happy laugh cuoi'], ['😁', 'beam grin'],
    ['😆', 'laugh haha'], ['😅', 'sweat smile'], ['🤣', 'rofl lol haha'], ['😂', 'joy tears laugh khoc cuoi'],
    ['🙂', 'slight smile'], ['🙃', 'upside down'], ['😉', 'wink nhay mat'], ['😊', 'blush smile'],
    ['😇', 'angel innocent'], ['🥰', 'love hearts yeu'], ['😍', 'heart eyes love yeu'], ['🤩', 'star struck wow'],
    ['😘', 'kiss hon'], ['😗', 'kiss'], ['😚', 'kiss'], ['😙', 'kiss'], ['😋', 'yum ngon'],
    ['😛', 'tongue le luoi'], ['😜', 'wink tongue'], ['🤪', 'zany crazy'], ['😝', 'tongue'],
    ['🤑', 'money tien'], ['🤗', 'hug om'], ['🤭', 'giggle'], ['🤫', 'shush quiet im'], ['🤔', 'think suy nghi'],
    ['🤐', 'zipper quiet'], ['🤨', 'raised eyebrow'], ['😐', 'neutral'], ['😑', 'expressionless'],
    ['😶', 'no mouth'], ['😏', 'smirk'], ['😒', 'unamused'], ['🙄', 'eye roll'], ['😬', 'grimace'],
    ['😌', 'relieved'], ['😔', 'pensive sad buon'], ['😪', 'sleepy buon ngu'], ['😴', 'sleep ngu'],
    ['😷', 'mask om'], ['🤒', 'sick om sot'], ['🤕', 'hurt injured'], ['🤮', 'vomit non'], ['🤧', 'sneeze'],
    ['🥵', 'hot nong'], ['🥶', 'cold lanh'], ['😵', 'dizzy'], ['🤯', 'mind blown wow'], ['🤠', 'cowboy'],
    ['🥳', 'party tiec mung'], ['😎', 'cool sunglasses ngau'], ['🤓', 'nerd geek'], ['🧐', 'monocle'],
    ['😕', 'confused'], ['😟', 'worried lo lang'], ['🙁', 'frown'], ['😮', 'surprised ngac nhien'],
    ['😯', 'hushed'], ['😲', 'astonished'], ['😳', 'flushed'], ['🥺', 'pleading nai ni'],
    ['😦', 'frown'], ['😧', 'anguished'], ['😨', 'fearful so'], ['😰', 'anxious'], ['😥', 'sad'],
    ['😢', 'cry khoc'], ['😭', 'sob khoc'], ['😱', 'scream so hai'], ['😖', 'confounded'],
    ['😣', 'persevere'], ['😞', 'disappointed buon'], ['😓', 'downcast sweat'], ['😩', 'weary met'],
    ['😫', 'tired met'], ['😤', 'triumph huff'], ['😡', 'rage angry gian'], ['😠', 'angry gian'],
    ['🤬', 'cursing chui'], ['😈', 'devil imp'], ['👿', 'angry devil'], ['💀', 'skull chet'],
    ['💩', 'poop'], ['🤡', 'clown he'], ['👻', 'ghost ma'], ['👽', 'alien nguoi ngoai hanh tinh'],
    ['🤖', 'robot'], ['😺', 'cat'], ['😸', 'cat'], ['😻', 'cat love'], ['🙀', 'cat scream'],
  ],
  people: [
    ['👋', 'wave hello chao'], ['🤚', 'hand'], ['✋', 'hand stop'], ['🖐️', 'hand'], ['👌', 'ok'],
    ['🤌', 'pinch'], ['✌️', 'victory peace'], ['🤞', 'crossed fingers may man'], ['🤟', 'love you'],
    ['🤘', 'rock'], ['👈', 'left'], ['👉', 'right'], ['👆', 'up'], ['👇', 'down'], ['☝️', 'point up'],
    ['👍', 'thumbs up like dong y tot'], ['👎', 'thumbs down dislike'], ['✊', 'fist'], ['👊', 'punch'],
    ['🤛', 'fist left'], ['🤜', 'fist right'], ['👏', 'clap vo tay'], ['🙌', 'raise hands hooray'],
    ['👐', 'open hands'], ['🤲', 'palms'], ['🙏', 'pray thanks cam on please'], ['🤝', 'handshake bat tay deal'],
    ['💪', 'muscle strong manh'], ['🫶', 'heart hands'], ['✍️', 'writing viet'], ['👀', 'eyes nhin'],
    ['🧠', 'brain nao'], ['👶', 'baby em be'], ['🧑', 'person'], ['👨', 'man'], ['👩', 'woman'],
    ['🧒', 'child'], ['👦', 'boy'], ['👧', 'girl'], ['👴', 'old man'], ['👵', 'old woman'],
    ['👮', 'police'], ['👷', 'worker cong nhan'], ['💂', 'guard'], ['🕵️', 'detective spy'],
    ['👨‍💻', 'developer coder lap trinh'], ['👩‍💻', 'developer coder'], ['👨‍🔧', 'mechanic'],
    ['🧑‍💼', 'office worker'], ['👨‍🎓', 'student graduate'], ['🦸', 'hero'], ['🦹', 'villain'],
  ],
  animals: [
    ['🐶', 'dog cho'], ['🐱', 'cat meo'], ['🐭', 'mouse chuot'], ['🐹', 'hamster'], ['🐰', 'rabbit tho'],
    ['🦊', 'fox cao'], ['🐻', 'bear gau'], ['🐼', 'panda'], ['🐨', 'koala'], ['🐯', 'tiger ho'],
    ['🦁', 'lion su tu'], ['🐮', 'cow bo'], ['🐷', 'pig heo lon'], ['🐸', 'frog ech'], ['🐵', 'monkey khi'],
    ['🐔', 'chicken ga'], ['🐧', 'penguin'], ['🐦', 'bird chim'], ['🦆', 'duck vit'], ['🦅', 'eagle dai bang'],
    ['🦉', 'owl cu'], ['🐺', 'wolf soi'], ['🐗', 'boar'], ['🐴', 'horse ngua'], ['🦄', 'unicorn'],
    ['🐝', 'bee ong'], ['🐛', 'bug sau'], ['🦋', 'butterfly buom'], ['🐌', 'snail oc sen'], ['🐞', 'ladybug'],
    ['🐜', 'ant kien'], ['🕷️', 'spider nhen'], ['🐢', 'turtle rua'], ['🐍', 'snake ran'], ['🦖', 'dino'],
    ['🐙', 'octopus bach tuoc'], ['🐠', 'fish ca'], ['🐬', 'dolphin ca heo'], ['🐳', 'whale ca voi'],
    ['🦈', 'shark ca map'], ['🐊', 'crocodile ca sau'], ['🐘', 'elephant voi'], ['🦒', 'giraffe huou'],
    ['🐪', 'camel lac da'], ['🐎', 'horse'], ['🌵', 'cactus xuong rong'], ['🌲', 'tree cay thong'],
    ['🌳', 'tree cay'], ['🌴', 'palm tree dua'], ['🌱', 'seedling mam'], ['🌿', 'herb la'],
    ['🍀', 'clover co bon la may man'], ['🌸', 'blossom hoa'], ['🌹', 'rose hoa hong'], ['🌻', 'sunflower hoa huong duong'],
    ['🌼', 'flower hoa'], ['🌷', 'tulip'], ['🍁', 'maple leaf la phong'], ['🍄', 'mushroom nam'],
    ['🌍', 'earth trai dat'], ['⭐', 'star sao'], ['🌟', 'star sao'], ['✨', 'sparkles lap lanh'],
    ['⚡', 'lightning set'], ['🔥', 'fire lua hot'], ['🌈', 'rainbow cau vong'], ['☀️', 'sun mat troi'],
    ['🌙', 'moon mat trang'], ['☁️', 'cloud may'], ['❄️', 'snow tuyet'], ['💧', 'water drop nuoc'],
  ],
  food: [
    ['🍏', 'apple tao'], ['🍎', 'apple tao'], ['🍐', 'pear le'], ['🍊', 'orange cam'], ['🍋', 'lemon chanh'],
    ['🍌', 'banana chuoi'], ['🍉', 'watermelon dua hau'], ['🍇', 'grapes nho'], ['🍓', 'strawberry dau'],
    ['🫐', 'blueberry'], ['🍒', 'cherry'], ['🍑', 'peach dao'], ['🥭', 'mango xoai'], ['🍍', 'pineapple dua'],
    ['🥥', 'coconut dua'], ['🥝', 'kiwi'], ['🍅', 'tomato ca chua'], ['🥑', 'avocado bo'], ['🥦', 'broccoli'],
    ['🥕', 'carrot ca rot'], ['🌽', 'corn ngo bap'], ['🌶️', 'pepper ot'], ['🥔', 'potato khoai'],
    ['🍞', 'bread banh mi'], ['🥐', 'croissant'], ['🥖', 'baguette'], ['🧀', 'cheese pho mai'],
    ['🥚', 'egg trung'], ['🍳', 'fried egg trung op'], ['🥞', 'pancake'], ['🥓', 'bacon'],
    ['🍔', 'burger hamburger'], ['🍟', 'fries khoai chien'], ['🍕', 'pizza'], ['🌭', 'hotdog'],
    ['🥪', 'sandwich'], ['🌮', 'taco'], ['🌯', 'burrito'], ['🍝', 'pasta mi y'], ['🍜', 'ramen mi'],
    ['🍲', 'stew lau'], ['🍛', 'curry rice com'], ['🍣', 'sushi'], ['🍱', 'bento'], ['🍚', 'rice com'],
    ['🍙', 'rice ball'], ['🍢', 'oden'], ['🍡', 'dango'], ['🍧', 'shaved ice'], ['🍨', 'ice cream kem'],
    ['🍦', 'ice cream kem'], ['🍰', 'cake banh'], ['🎂', 'birthday cake banh sinh nhat'], ['🧁', 'cupcake'],
    ['🍮', 'pudding'], ['🍫', 'chocolate socola'], ['🍬', 'candy keo'], ['🍭', 'lollipop keo'],
    ['🍩', 'donut'], ['🍪', 'cookie banh quy'], ['☕', 'coffee ca phe'], ['🍵', 'tea tra'],
    ['🧃', 'juice nuoc'], ['🥤', 'soda nuoc ngot'], ['🍺', 'beer bia'], ['🍻', 'beers bia'],
    ['🍷', 'wine ruou'], ['🥂', 'champagne'], ['🍸', 'cocktail'], ['🍶', 'sake'],
  ],
  activity: [
    ['⚽', 'soccer bong da'], ['🏀', 'basketball bong ro'], ['🏈', 'football'], ['⚾', 'baseball'],
    ['🎾', 'tennis'], ['🏐', 'volleyball bong chuyen'], ['🏉', 'rugby'], ['🎱', 'billiards bi a'],
    ['🏓', 'ping pong bong ban'], ['🏸', 'badminton cau long'], ['🥅', 'goal'], ['🏒', 'hockey'],
    ['🏑', 'field hockey'], ['🏏', 'cricket'], ['⛳', 'golf'], ['🏹', 'archery cung'], ['🎣', 'fishing cau ca'],
    ['🥊', 'boxing'], ['🥋', 'martial arts vo'], ['⛸️', 'skating truot bang'], ['🎿', 'ski'],
    ['🛷', 'sled'], ['🏂', 'snowboard'], ['🏋️', 'weight lifting ta'], ['🤸', 'gymnastics'],
    ['🤺', 'fencing'], ['🤾', 'handball'], ['🏌️', 'golfer'], ['🏇', 'horse racing dua ngua'],
    ['🧘', 'yoga thien'], ['🏄', 'surf luot song'], ['🏊', 'swim boi'], ['🚴', 'cycling dap xe'],
    ['🚵', 'mountain bike'], ['🏆', 'trophy cup giai thuong'], ['🥇', 'gold medal vang'], ['🥈', 'silver medal bac'],
    ['🥉', 'bronze medal dong'], ['🏅', 'medal huy chuong'], ['🎖️', 'medal'], ['🎯', 'target dart muc tieu'],
    ['🎮', 'game controller'], ['🕹️', 'joystick'], ['🎲', 'dice xuc xac'], ['🎳', 'bowling'],
    ['🎨', 'art palette ve'], ['🎭', 'theater kich'], ['🎬', 'movie phim'], ['🎤', 'mic karaoke'],
    ['🎧', 'headphone tai nghe'], ['🎼', 'music note nhac'], ['🎵', 'music nhac'], ['🎸', 'guitar'],
    ['🎹', 'piano'], ['🥁', 'drum trong'], ['🎺', 'trumpet ken'], ['🎻', 'violin'], ['🪕', 'banjo'],
    ['🎷', 'saxophone'], ['🎺', 'trumpet'], ['🎪', 'circus xiec'], ['🎉', 'party tiec mung'],
    ['🎊', 'confetti'], ['🎈', 'balloon bong bay'], ['🎁', 'gift qua tang'], ['🎀', 'ribbon no'],
  ],
  travel: [
    ['🚗', 'car xe hoi oto'], ['🚕', 'taxi'], ['🚙', 'suv xe'], ['🚌', 'bus xe buyt'], ['🚎', 'trolley'],
    ['🏎️', 'race car xe dua'], ['🚓', 'police car'], ['🚑', 'ambulance cuu thuong'], ['🚒', 'fire truck cuu hoa'],
    ['🚚', 'truck xe tai'], ['🚛', 'truck'], ['🚜', 'tractor'], ['🛵', 'scooter xe may'], ['🏍️', 'motorcycle xe may'],
    ['🚲', 'bicycle xe dap'], ['🛴', 'scooter'], ['🚆', 'train tau'], ['🚄', 'high speed train tau cao toc'],
    ['🚈', 'metro tau dien'], ['🚉', 'station ga'], ['✈️', 'airplane may bay'], ['🛫', 'takeoff cat canh'],
    ['🛬', 'landing ha canh'], ['🚀', 'rocket ten lua'], ['🛸', 'ufo dia bay'], ['🚁', 'helicopter truc thang'],
    ['⛵', 'sailboat thuyen'], ['🚤', 'speedboat ca no'], ['🛳️', 'ship tau'], ['⚓', 'anchor mo neo'],
    ['🚧', 'construction'], ['⛽', 'fuel xang'], ['🚦', 'traffic light den giao thong'], ['🗺️', 'map ban do'],
    ['🗿', 'moai'], ['🗽', 'statue liberty'], ['🗼', 'tower thap'], ['🏰', 'castle lau dai'],
    ['🏯', 'castle'], ['🏟️', 'stadium san van dong'], ['🎡', 'ferris wheel'], ['🎢', 'roller coaster'],
    ['🎠', 'carousel'], ['⛲', 'fountain'], ['⛱️', 'beach umbrella bai bien'], ['🏖️', 'beach bai bien'],
    ['🏝️', 'island dao'], ['🏔️', 'mountain nui'], ['⛰️', 'mountain nui'], ['🌋', 'volcano nui lua'],
    ['🏕️', 'camping'], ['🏠', 'house nha'], ['🏡', 'home nha'], ['🏢', 'office building toa nha'],
    ['🏥', 'hospital benh vien'], ['🏦', 'bank ngan hang'], ['🏫', 'school truong'], ['🏪', 'store cua hang'],
    ['⛪', 'church nha tho'], ['🕌', 'mosque'], ['🌃', 'night city thanh pho dem'], ['🌉', 'bridge cau'],
  ],
  objects: [
    ['⌚', 'watch dong ho'], ['📱', 'phone dien thoai'], ['💻', 'laptop may tinh'], ['⌨️', 'keyboard ban phim'],
    ['🖥️', 'desktop may tinh'], ['🖨️', 'printer may in'], ['🖱️', 'mouse chuot'], ['💾', 'floppy luu save'],
    ['💿', 'cd disc'], ['📀', 'dvd'], ['📷', 'camera may anh'], ['📸', 'camera flash'], ['🎥', 'video camera'],
    ['📹', 'video'], ['📞', 'phone'], ['☎️', 'telephone'], ['📟', 'pager'], ['📠', 'fax'], ['📺', 'tv'],
    ['📻', 'radio'], ['🔋', 'battery pin'], ['🔌', 'plug dien'], ['💡', 'bulb idea bong den y tuong'],
    ['🔦', 'flashlight den pin'], ['🕯️', 'candle nen'], ['🧯', 'extinguisher'], ['🛢️', 'oil dau'],
    ['💸', 'money flying tien'], ['💵', 'dollar tien'], ['💴', 'yen'], ['💶', 'euro'], ['💰', 'money bag tien'],
    ['💳', 'credit card the'], ['🧾', 'receipt hoa don'], ['💎', 'gem kim cuong'], ['⚖️', 'scale can'],
    ['🔧', 'wrench co le'], ['🔨', 'hammer bua'], ['⚒️', 'tools'], ['🛠️', 'tools dung cu'], ['⚙️', 'gear banh rang cau hinh'],
    ['🔩', 'nut bolt oc vit'], ['🧰', 'toolbox'], ['🧲', 'magnet nam cham'], ['🔫', 'gun sung'],
    ['💊', 'pill thuoc'], ['💉', 'syringe tiem'], ['🩺', 'stethoscope'], ['🔬', 'microscope kinh hien vi'],
    ['🔭', 'telescope kinh thien van'], ['📡', 'satellite antenna ve tinh'], ['🧬', 'dna'], ['🧪', 'test tube thi nghiem'],
    ['🌡️', 'thermometer nhiet ke'], ['🧹', 'broom choi'], ['🔑', 'key chia khoa'], ['🗝️', 'old key'],
    ['🔒', 'lock khoa'], ['🔓', 'unlock mo khoa'], ['🔐', 'locked key'], ['📦', 'package hop'],
    ['📮', 'mailbox'], ['📫', 'mailbox thu'], ['✉️', 'envelope thu mail'], ['📧', 'email mail'],
    ['📨', 'incoming mail'], ['📝', 'memo note ghi chu'], ['📄', 'page document tai lieu'], ['📃', 'page'],
    ['📑', 'bookmark tabs'], ['📊', 'bar chart bieu do'], ['📈', 'chart up tang'], ['📉', 'chart down giam'],
    ['📋', 'clipboard'], ['📌', 'pin ghim'], ['📍', 'pin location vi tri'], ['🖇️', 'paperclip'],
    ['📎', 'paperclip dinh kem'], ['✂️', 'scissors keo'], ['📏', 'ruler thuoc'], ['📐', 'triangle ruler'],
    ['📚', 'books sach'], ['📖', 'book sach'], ['📕', 'book do'], ['📗', 'book xanh'], ['📘', 'book'],
    ['🔖', 'bookmark danh dau'], ['🏷️', 'label nhan tag'], ['📅', 'calendar lich'], ['📆', 'calendar lich'],
    ['🗓️', 'calendar'], ['🗂️', 'folder thu muc'], ['📁', 'folder thu muc'], ['📂', 'folder open'],
    ['🗄️', 'file cabinet'], ['🗑️', 'trash thung rac xoa'], ['⏰', 'alarm bao thuc'], ['⏱️', 'stopwatch'],
    ['⏳', 'hourglass dong ho cat'], ['🔔', 'bell chuong thong bao'], ['🔕', 'mute tat chuong'],
  ],
  symbols: [
    ['❤️', 'heart red love yeu tim'], ['🧡', 'orange heart'], ['💛', 'yellow heart'], ['💚', 'green heart'],
    ['💙', 'blue heart'], ['💜', 'purple heart'], ['🖤', 'black heart'], ['🤍', 'white heart'],
    ['🤎', 'brown heart'], ['💔', 'broken heart tan vo'], ['❣️', 'heart'], ['💕', 'two hearts'],
    ['💞', 'hearts'], ['💓', 'beating heart'], ['💗', 'growing heart'], ['💖', 'sparkling heart'],
    ['💘', 'heart arrow'], ['💝', 'heart gift'], ['💟', 'heart decoration'], ['✅', 'check tick dung xong'],
    ['☑️', 'checkbox'], ['✔️', 'check tick'], ['❌', 'cross x sai'], ['❎', 'cross'], ['➕', 'plus cong them'],
    ['➖', 'minus tru'], ['➗', 'divide chia'], ['✖️', 'multiply nhan'], ['❓', 'question hoi'],
    ['❔', 'question'], ['❗', 'exclamation cham than'], ['❕', 'exclamation'], ['‼️', 'double exclamation'],
    ['⚠️', 'warning canh bao'], ['🚫', 'no cam'], ['⛔', 'no entry cam'], ['🔞', 'no 18'],
    ['💯', 'hundred 100 perfect'], ['🔥', 'fire hot lua'], ['⭐', 'star sao'], ['🌟', 'star'],
    ['✨', 'sparkles'], ['💫', 'dizzy'], ['💥', 'boom no'], ['💢', 'anger gian'], ['💦', 'sweat'],
    ['💨', 'dash gio'], ['🕐', 'clock gio'], ['🔄', 'refresh lam moi'], ['🔁', 'repeat lap'],
    ['🔀', 'shuffle'], ['▶️', 'play phat'], ['⏸️', 'pause tam dung'], ['⏹️', 'stop dung'],
    ['⏭️', 'next'], ['⏮️', 'previous'], ['🔼', 'up'], ['🔽', 'down'], ['⏫', 'fast up'], ['⏬', 'fast down'],
    ['➡️', 'arrow right phai'], ['⬅️', 'arrow left trai'], ['⬆️', 'arrow up len'], ['⬇️', 'arrow down xuong'],
    ['↗️', 'arrow'], ['↘️', 'arrow'], ['↙️', 'arrow'], ['↖️', 'arrow'], ['🔝', 'top'], ['🔙', 'back'],
    ['🆕', 'new moi'], ['🆗', 'ok'], ['🆙', 'up'], ['🆒', 'cool'], ['🆓', 'free'], ['🔟', 'ten'],
    ['#️⃣', 'hash'], ['*️⃣', 'asterisk'], ['0️⃣', 'zero'], ['1️⃣', 'one'], ['2️⃣', 'two'], ['3️⃣', 'three'],
    ['💲', 'dollar'], ['💱', 'currency'], ['©️', 'copyright'], ['®️', 'registered'], ['™️', 'trademark'],
    ['🔴', 'red circle do'], ['🟠', 'orange circle cam'], ['🟡', 'yellow circle vang'], ['🟢', 'green circle xanh'],
    ['🔵', 'blue circle xanh'], ['🟣', 'purple circle tim'], ['⚫', 'black circle den'], ['⚪', 'white circle trang'],
    ['🟥', 'red square'], ['🟩', 'green square'], ['🟦', 'blue square'], ['🟨', 'yellow square'],
    ['🔶', 'diamond'], ['🔷', 'diamond'], ['🔸', 'diamond'], ['🔹', 'diamond'], ['💠', 'diamond'],
  ],
  flags: [
    ['🏁', 'checkered flag dich finish'], ['🚩', 'flag co'], ['🎌', 'crossed flags'], ['🏴', 'black flag'],
    ['🏳️', 'white flag'], ['🏳️‍🌈', 'rainbow flag pride'], ['🇻🇳', 'vietnam viet nam'], ['🇺🇸', 'usa america my'],
    ['🇯🇵', 'japan nhat ban'], ['🇰🇷', 'korea han quoc'], ['🇨🇳', 'china trung quoc'], ['🇬🇧', 'uk england anh'],
    ['🇫🇷', 'france phap'], ['🇩🇪', 'germany duc'], ['🇮🇹', 'italy y'], ['🇪🇸', 'spain tay ban nha'],
    ['🇷🇺', 'russia nga'], ['🇮🇳', 'india an do'], ['🇧🇷', 'brazil'], ['🇨🇦', 'canada'],
    ['🇦🇺', 'australia uc'], ['🇸🇬', 'singapore'], ['🇹🇭', 'thailand thai lan'], ['🇲🇾', 'malaysia'],
    ['🇮🇩', 'indonesia'], ['🇵🇭', 'philippines'], ['🇭🇰', 'hong kong'], ['🇹🇼', 'taiwan dai loan'],
  ],
};

// Phẳng hoá để tìm kiếm theo từ khoá.
export const EMOJI_ALL: { c: string; k: string }[] = Object.values(EMOJIS).flat().map(([c, k]) => ({ c, k }));
